-- Tabla de cursos de solo lectura para el TP 4.
-- Se ejecuta desde el SQL Editor del proyecto de Supabase.

create table cursos (
  id bigint generated by default as identity primary key,
  nombre text not null,
  profesor text,
  nivel text,
  cupo integer check (cupo between 1 and 60),
  descripcion text,
  creado_en timestamptz not null default now()
);

insert into cursos (nombre, profesor, nivel, cupo, descripcion) values
  ('Álgebra y Geometría Analítica', 'Ing. Jesús González', 'inicial', 45,
   'Vectores, matrices y sistemas de ecuaciones aplicados a gráficos por computadora.'),
  ('Bases de Datos Relacionales', 'Prof. Rodrigo Alday', 'intermedio', 30,
   'Modelo entidad-relación, normalización y consultas SQL sobre PostgreSQL.'),
  ('Desarrollo Web Semipresencial', 'Ing. Jesús González', 'intermedio', 40,
   'HTML, CSS y JavaScript moderno hasta llegar a React con Vite.'),
  ('Laboratorio de Programación', 'Prof. Marina Quiroga', 'inicial', 35,
   'Primeros algoritmos, estructuras de control y buenas prácticas de código.'),
  ('Redes y Comunicación de Datos', 'Ing. Pablo Sosa', 'intermedio', 25,
   'Modelo OSI, direccionamiento IP y configuración de redes locales.'),
  ('Seguridad Informática', 'Lic. Carla Ferreyra', 'avanzado', 20,
   'Criptografía aplicada, control de accesos y análisis de vulnerabilidades.');

alter table cursos enable row level security;

-- Provisorio: la Clase 5 reemplaza el using (true) por una política real.
create policy "lectura publica de cursos" on cursos
  for select to anon, authenticated using (true);
