-- Tabla de notas atada al usuario logueado.
-- Se ejecuta desde el SQL Editor del proyecto de Supabase.

create table notas (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id),
  contenido text not null
);

alter table notas enable row level security;

create policy "cada usuario ve solo sus notas" on notas
  for select to authenticated using (auth.uid() = user_id);

create policy "cada usuario crea sus notas" on notas
  for insert to authenticated with check (auth.uid() = user_id);

create policy "cada usuario edita sus notas" on notas
  for update to authenticated using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "cada usuario borra sus notas" on notas
  for delete to authenticated using (auth.uid() = user_id);
