-- Tabla de publicaciones para el trabajo integrador final.
-- Es una tabla simple, sin dueño: no usa user_id ni auth.uid().
-- Se ejecuta desde el SQL Editor del proyecto de Supabase.

create table publicaciones (
  id bigint generated by default as identity primary key,
  titulo text not null,
  contenido text not null,
  creado_en timestamptz default now()
);

-- El TP no pide seguridad de acceso, pero el proyecto ya tiene RLS activo en notas
-- y Supabase marca como error las tablas públicas sin RLS. Se usa entonces la opción
-- que permite el enunciado: RLS activado con una única política abierta.
alter table publicaciones enable row level security;

create policy "acceso abierto a las publicaciones" on publicaciones
  for all using (true) with check (true);
